# Generated by Django 6.1.1 on 2026-09-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('mrr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monthly Recurring Revenue')),
                ('arr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Recurring Revenue')),
                ('churn_rate', models.FloatField(default=0.0, help_text='Percentage churn value')),
                ('active_subscriptions_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEW', 'New Subscription'), ('UPGRADE', 'Plan Upgrade'), ('DOWNGRADE', 'Plan Downgrade'), ('CHURN', 'Cancellation')], max_length=15)),
                ('mrr_impact', models.DecimalField(decimal_places=2, help_text='Monthly value variance (+/-)', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
